[package]
name = "backstop"
description = "a desktop music player built w/ rust"
repository = "https://github.com/iwantpizza10/backstop"
license = "MIT"
version = "3.0.0"
edition = "2024"

[dependencies]

[build-dependencies]

[lints.clippy]
allow_attributes = "warn"
branches_sharing_code = "warn"
case_sensitive_file_extension_comparisons = "warn"
cast_lossless = "warn"
clone_on_ref_ptr = "warn"
collapsible_else_if = "warn"
collection_is_never_read = "warn"
comparison_chain = "warn"
elidable_lifetime_names = "warn"
filetype_is_file = "warn"
implicit_clone = "warn"
manual_instant_elapsed = "warn"
needless_collect = "warn"
search_is_some = "warn"
todo = "warn"
unnecessary_semicolon = "warn"
unnecessary_wraps = "warn"
