import { MenuState } from "../types.slint";
import { Button, HorizontalBox } from "std-widgets.slint";

export component FirstButtonsView {
    in-out property <MenuState> menustate;
    in property <bool> onboarding;
    callback add_media_directory();
    callback rescan_library();

    width: 1366px;

    VerticalLayout {
        spacing: 64px;
        padding-bottom: 128px;

        HorizontalLayout {
            width: 100%;
            alignment: center;

            Image {
                source: @image-url("../res/backstopfull.png");
                width: 512px;
                horizontal-alignment: center;
            }
        }

        VerticalLayout {
            Text {
                horizontal-alignment: center;
                text: onboarding ? "Looks like you're new here!" : "Welcome back!";
                font-size: 48px;
            }

            Text {
                text: onboarding ? "Welcome to Backstop. Get started by:" : "Welcome back to Backstop. Get started again by:";
                horizontal-alignment: center;
                font-size: 24px;
            }

            HorizontalLayout {
                alignment: center;
                padding-top: 64px;
                spacing: 16px;

                Button {
                    text: "Add a Media Directory";

                    clicked => { add_media_directory() }
                }

                Button {
                    text: "Scan Library";
                    
                    clicked => { rescan_library() }
                }

                Button {
                    text: "Close";

                    clicked => {
                        menustate = MenuState.Main
                    }
                }
            }
        }
    }
}
