import { MenuState } from "../types.slint";
import { Button, HorizontalBox } from "std-widgets.slint";

export component TextView {
    in property <string> text;
    in property <string> subtext;

    width: 1366px;

    VerticalLayout {
        spacing: 64px;
        padding-bottom: 128px;

        HorizontalLayout {
            width: 100%;
            alignment: center;

            Image {
                source: @image-url("../res/backstopfull.png");
                width: 512px;
                horizontal-alignment: center;
            }
        }

        VerticalLayout {
            Text {
                horizontal-alignment: center;
                text: text;
                font-size: 48px;
            }

            Text {
                text: subtext;
                horizontal-alignment: center;
                font-size: 24px;
            }
        }
    }
}
