import { MenuState, LibrarySong } from "./types.slint";
import { Button, Slider, ProgressIndicator } from "std-widgets.slint";
import { IconDisplay, IconSet, Icon } from "@lucide";

component FooterButton {
    in property <Icon> icon;
    in property <color> color;
    in property <color> bg_color;
    callback clicked();

    TouchArea {
        width: 42px;
        height: 42px;

        Rectangle {
            width: 100%;
            height: 100%;
            background: bg_color;
            border-radius: 10px;
        }

        IconDisplay {
            icon: icon;
            stroke: color;
            stroke-fill: @linear-gradient(0deg, color 0%, color 100%);
        }

        clicked => { clicked() }
    }
}

export component FooterBar {
    callback set_volume(float);
    callback toggle_shuffle();
    callback toggle_repeat();
    callback skip_backward();
    callback skip_forward();
    callback toggle_peek();
    callback resume();
    callback pause();
    in-out property <MenuState> menustate;
    in property <LibrarySong> current_song;
    in property <color> background;
    in property <color> button_disabled_color;
    in property <color> button_enabled_color;
    in property <float> volume;
    in property <float> playback_speed;
    in property <bool> playing;
    in property <bool> shuffle;
    in property <bool> paused;
    in property <bool> repeat;
    in property <bool> peek;
    in property <int> song_position;

    pure function padded_int(number: int) -> string {
        if number >= 10 {
            return "\{number}";
        } else {
            return "0\{number}";
        }
    }

    pure function seconds_to_timestamp(seconds: int) -> string {
        return Math.floor(seconds / 60) + ":" + padded_int(Math.mod(seconds, 60));
    }

    Rectangle {
        width: 1366px;
        height: 96px;
        background: background;
    }

    HorizontalLayout {
        HorizontalLayout {
            padding-left: 4px;
            min-width: 1366px / 3;
            max-width: 1366px / 3;
            spacing: 8px;

            Rectangle {
                border-radius: 10px;
                width: 88px; // from 96px header width - 8px
                clip: true;

                TouchArea {
                    width: 88px;
                    height: 88px;

                    clicked => { menustate = MenuState.CoverArt }
                }

                Image {
                    width: 88px;
                    height: self.width;
                    source: current_song.cover;
                }
            }

            VerticalLayout {
                alignment: center;
                spacing: 8px;

                Text {
                    text: current_song.title;
                    font-size: 18px;
                }

                VerticalLayout {
                    spacing: -2px;

                    if !current_song.album.is-empty: Text {
                        text: current_song.track-number != -1 ? "\{current_song.album} #\{current_song.track-number}" : "\{current_song.album}";
                        font-size: 12px;
                    }

                    Text {
                        text: "\{current_song.artist}";
                        font-size: 12px;
                    }
                }
            }
        }

        VerticalLayout {
            min-width: 1366px / 3;
            max-width: 1366px / 3;
            height: 96px;
            alignment: center;
            spacing: 32px;
            padding-bottom: 24px;

            HorizontalLayout {
                spacing: 8px;
                alignment: center;

                Text {
                    text: seconds_to_timestamp(song_position);
                    horizontal-alignment: right;
                    vertical-alignment: center;
                }

                ProgressIndicator {
                    progress: song_position / (current_song.length / playback_speed);
                    height: 8px;
                    width: 256px;
                }

                Text {
                    text: seconds_to_timestamp(Math.floor(current_song.length / playback_speed));
                    horizontal-alignment: left;
                    vertical-alignment: center;
                }
            }

            HorizontalLayout {
                spacing: -160px;

                FooterButton {
                    icon: IconSet.Shuffle;
                    color: shuffle ? #ffffff : #999999;
                    bg_color: shuffle ? button_enabled_color : button_disabled_color;

                    clicked => { toggle_shuffle() }
                }

                FooterButton {
                    icon: IconSet.ArrowBigLeftDash;
                    color: #ffffff;
                    bg_color: button_enabled_color;

                    clicked => { skip_backward() }
                }

                FooterButton {
                    icon: paused ? IconSet.Play : IconSet.Pause;
                    color: #ffffff;
                    bg_color: button_enabled_color;

                    clicked => {
                        if paused {
                            resume()
                        } else {
                            pause()
                        }
                    }
                }

                FooterButton {
                    icon: IconSet.ArrowBigRightDash;
                    color: #ffffff;
                    bg_color: button_enabled_color;

                    clicked => { skip_forward() }
                }

                FooterButton {
                    icon: IconSet.Repeat;
                    color: repeat ? #ffffff : #999999;
                    bg_color: repeat ? button_enabled_color : button_disabled_color;

                    clicked => { toggle_repeat() }
                }

                FooterButton {
                    icon: IconSet.ListPlus;
                    color: peek ? #ffffff : #999999;
                    bg_color: peek ? button_enabled_color : button_disabled_color;

                    clicked => { toggle_peek() }
                }
            }
        }

        HorizontalLayout {
            min-width: 1366px / 3;
            max-width: 1366px / 3;
            alignment: end;
            padding-right: 27px; // uhh smth smth (96px footer height - 42px button height) / 2 = 27px per side
            spacing: 8px;

            VerticalLayout {
                height: 96px;
                alignment: center;
                spacing: 10px;

                Text {
                    text: "\{volume} dB (\{Math.floor(Math.pow(10, volume / 20) * 100)}%)";
                    font-size: 12px;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                Slider {
                    value: volume + 40;
                    minimum: 0;
                    maximum: 40;
                    width: 100px;
                    height: 4px;

                    changed(value) => { set_volume(Math.floor(value - 40)) }
                }
            }

            FooterButton {
                width: 42px;
                icon: IconSet.Settings2;
                color: #ffffff;
                bg_color: button_disabled_color;

                clicked => { menustate = MenuState.Settings }
            }

            // Image {
            //     source: @image-url("./res/backstopoutline.png");
            //     width: 64px;
            // }
        }
    }
}
