import { MenuState, LibrarySong } from "./types.slint";
import { Button } from "std-widgets.slint";
import { OnboardingView } from "views/onboarding.slint";
import { MainView } from "views/main.slint";
import { FooterBar } from "footer.slint";

export component BackstopWindow inherits Window {
    in-out property <MenuState> menustate: Init;
    in-out property <int> song_position: 0;
    in property <[LibrarySong]> media_library;
    in property <LibrarySong> current_song;
    in property <[string]> media_directories;
    in property <float> volume;
    in property <bool> playing: false;
    in property <bool> shuffle: false;
    in property <bool> paused: false;
    in property <bool> repeat: false;
    callback add_media_directory();
    callback rescan_library();
    callback pause();
    callback resume();
    callback seek(int);
    callback toggle_shuffle();
    callback skip_backward();
    callback skip_forward();
    callback toggle_repeat();
    callback set_volume(float);
    callback play_song(LibrarySong);

    title: "Backstop";
    width: 1366px;
    height: 768px;
    background: #112233;

    Timer {
        interval: 1s;
        running: song_position != current_song.length && !paused && playing;

        triggered => {
            song_position += 1;
        }
    }

    if menustate == MenuState.Onboarding: OnboardingView {
        menustate <=> menustate;

        add_media_directory => { add_media_directory() }
        rescan_library => { rescan_library() }
    }

    if menustate == MenuState.Main: MainView {
        media_library: media_library;

        play_song(a) => { play_song(a) }
    }

    FooterBar {
        x: 0px;
        y: 768px - self.height;
        height: 96px;

        menustate <=> menustate;
        current_song: current_song;
        volume: volume;
        playing: playing;
        shuffle: shuffle;
        paused: paused;
        repeat: repeat;
        song_position: song_position;

        set_volume(a) => { set_volume(a) }
        toggle_shuffle => { toggle_shuffle() }
        toggle_repeat => { toggle_repeat() }
        skip_backward => { skip_backward() }
        skip_forward => { skip_forward() }
        seek(a) => { seek(a) }
        resume => { resume() }
        pause => { pause() }
    }
}
