import { MenuState, LibrarySong, UIRichPresenceType } from "./types.slint";
import { Button } from "std-widgets.slint";
import { FirstButtonsView } from "views/firstbuttons.slint";
import { MainView } from "views/main.slint";
import { TextView } from "views/text.slint";
import { FooterBar } from "footer.slint";
import { SettingsView } from "views/settings.slint";
import { CoverArtView } from "views/coverart.slint";

export component BackstopWindow inherits Window {
    in-out property <MenuState> menustate: Init;
    in property <UIRichPresenceType> rpc_type;
    in property <[LibrarySong]> media_library;
    in property <LibrarySong> current_song;
    in property <[string]> media_directories;
    in property <[string]> next_three;
    in property <[string]> rpc_list;
    in property <float> volume;
    in property <float> playback_speed;
    in property <bool> playing: false;
    in property <bool> shuffle: false;
    in property <bool> paused: false;
    in property <bool> repeat: false;
    in property <int> song_position: 0;
    property <bool> peek;
    callback remove_media_directory(string);
    callback add_media_directory();
    callback add_rpc_list_item(string);
    callback remove_rpc_list_item(string);
    callback set_rpc_type(UIRichPresenceType);
    callback rescan_library();
    callback pause();
    callback resume();
    callback toggle_shuffle();
    callback skip_backward();
    callback skip_forward();
    callback toggle_repeat();
    callback set_volume(float);
    callback set_playback_speed(float);
    callback play_song(LibrarySong);

    title: "Backstop";
    icon: @image-url("./res/backstopshort_square.png");
    width: 1366px;
    height: 768px;
    background: #0b071b;

    if menustate == MenuState.Onboarding || menustate == MenuState.Welcome: FirstButtonsView {
        menustate <=> menustate;
        onboarding: menustate == MenuState.Onboarding;

        add_media_directory => { add_media_directory() }
        rescan_library => { rescan_library() }
    }

    if menustate == MenuState.Main: MainView {
        media_library: media_library;
        animation_tick: animation-tick();

        play_song(a) => { play_song(a) }
    }

    if menustate == MenuState.Settings: SettingsView {
        menustate <=> menustate;
        media_directories: media_directories;
        rpc_list: rpc_list;
        rpc_type: rpc_type;
        button_disabled_color: #4b0fa3;
        button_enabled_color: #7221ea;
        playback_speed: playback_speed;

        add_media_directory => { add_media_directory() }
        remove_media_directory(a) => { remove_media_directory(a) }
        set_playback_speed(a) => { set_playback_speed(a) }
        rescan_library => { rescan_library() }
        add_rpc_list_item(a) => { add_rpc_list_item(a) }
        remove_rpc_list_item(a) => { remove_rpc_list_item(a) }
        set_rpc_type(a) => { set_rpc_type(a) }
    }

    if menustate == MenuState.Reindexing || menustate == MenuState.AddingDir: TextView {
        text: menustate == MenuState.Reindexing ? "Reindexing library..." : "Adding directory...";
        subtext: "Please wait a moment...";
    }

    if menustate == MenuState.IndexingError || menustate == MenuState.LoadingError || menustate == MenuState.PlaybackError: TextView {
        text: (menustate == MenuState.LoadingError ? "Loading" : 
            menustate == MenuState.IndexingError ? "Indexing" :
            "Playback") + " error!";
        subtext: "Please try relaunching the app and/or checking disk permissions.";
    }

    if menustate == MenuState.CoverArt: CoverArtView {
        menustate <=> menustate;
        current_song: current_song;
    }

    if menustate != MenuState.Reindexing &&
        menustate != MenuState.AddingDir &&
        menustate != MenuState.IndexingError &&
        menustate != MenuState.LoadingError &&
        menustate != MenuState.PlaybackError: FooterBar {
        x: 0px;
        y: 768px - self.height;
        height: 96px;
        background: #170f37;
        button_disabled_color: #4b0fa3;
        button_enabled_color: #7221ea;

        menustate <=> menustate;
        current_song: current_song;
        volume: volume;
        playing: playing;
        shuffle: shuffle;
        paused: paused;
        repeat: repeat;
        song_position: song_position;
        playback_speed: playback_speed;
        peek: peek;

        set_volume(a) => { set_volume(a) }
        toggle_shuffle => { toggle_shuffle() }
        toggle_repeat => { toggle_repeat() }
        skip_backward => { skip_backward() }
        skip_forward => { skip_forward() }
        resume => { resume() }
        pause => { pause() }
        toggle_peek => { peek = !peek }
    }

    if peek: Rectangle {
        x: (1366px - self.width) / 2;
        y: (768px - self.height) / 2;
        width: 384px;
        height: 192px;

        background: #170f37;
        border-radius: 15px;
        border-color: white;
        border-width: 2px;
        clip: true;

        HorizontalLayout {
            alignment: center;

            VerticalLayout {
                padding-left: 32px;
                padding-right: 32px;
                alignment: center;
                spacing: 4px;

                Text {
                    text: "Next 3 Songs:\n";
                    font-size: 24px;
                    horizontal-alignment: center;
                }

                for i in 3: Text {
                    text: next_three[i];
                    horizontal-alignment: center;
                    wrap: TextWrap.word-wrap;
                }
            }
        }
    }
}
