import { MenuState, LibrarySong } from "./types.slint";
import { Button } from "std-widgets.slint";
import { OnboardingView } from "views/onboarding.slint";
import { MainView } from "views/main.slint";
import { FooterBar } from "footer.slint";
import { WelcomeView } from "views/welcome.slint";
import { SettingsView } from "views/settings.slint";

export component BackstopWindow inherits Window {
    in-out property <MenuState> menustate: Init;
    in property <[LibrarySong]> media_library;
    in property <LibrarySong> current_song;
    in property <[string]> media_directories;
    in property <float> volume;
    in property <float> playback_speed;
    in property <bool> playing: false;
    in property <bool> shuffle: false;
    in property <bool> paused: false;
    in property <bool> repeat: false;
    in property <int> song_position: 0;
    callback remove_media_directory(string);
    callback add_media_directory();
    callback rescan_library();
    callback pause();
    callback resume();
    callback toggle_shuffle();
    callback skip_backward();
    callback skip_forward();
    callback toggle_repeat(); // NOT added
    callback set_volume(float);
    callback set_playback_speed(float);
    callback play_song(LibrarySong);

    title: "Backstop";
    width: 1366px;
    height: 768px;
    background: #0b071b;

    if menustate == MenuState.Onboarding: OnboardingView {
        menustate <=> menustate;

        add_media_directory => { add_media_directory() }
        rescan_library => { rescan_library() }
    }

    // if menustate == MenuState.Welcome: WelcomeView {
        // menustate <=> menustate;

        // add_media_directory => { add_media_directory() }
        // rescan_library => { rescan_library() }
    // }

    if menustate == MenuState.Main: MainView {
        media_library: media_library;

        play_song(a) => { play_song(a) }
    }

    if menustate == MenuState.Settings: SettingsView {
        menustate <=> menustate;
        media_directories: media_directories;
        button_disabled_color: #4b0fa3;
        button_enabled_color: #7221ea;
        playback_speed: playback_speed;

        add_media_directory => { add_media_directory() }
        remove_media_directory(a) => { remove_media_directory(a) }
        set_playback_speed(a) => { set_playback_speed(a) }
        rescan_library => { rescan_library() }
    }

    FooterBar {
        x: 0px;
        y: 768px - self.height;
        height: 96px;
        background: #170f37;
        button_disabled_color: #4b0fa3;
        button_enabled_color: #7221ea;

        menustate <=> menustate;
        current_song: current_song;
        volume: volume;
        playing: playing;
        shuffle: shuffle;
        paused: paused;
        repeat: repeat;
        song_position: song_position;
        playback_speed: playback_speed;

        set_volume(a) => { set_volume(a) }
        toggle_shuffle => { toggle_shuffle() }
        toggle_repeat => { toggle_repeat() }
        skip_backward => { skip_backward() }
        skip_forward => { skip_forward() }
        resume => { resume() }
        pause => { pause() }
    }
}
