export enum MenuState {
    Init,
    Onboarding,
    Welcome,
    Main,
    Settings,
    Reindexing,
    AddingDir,
    IndexingError,
    LoadingError,
    PlaybackError,
    CoverArt
}

export struct LibrarySong {
    path: string,
    title: string,
    length: int,
    artist: string,
    album: string,
    album_artist: string,
    track_number: int,
    year: int,
    cover_path: string,
    cover: image
}

export enum UIRichPresenceType {
    Blacklist,
    Whitelist,
    Disabled
}
